@extends('vh::master')
@section('content')
@include('vh::static.headertop')
<div id="maincontent">
><h2 id="toc-services">Sử dụng Dịch vụ của chúng tôi</h2>
<p>Bạn phải tuân thủ mọi chính sách đã cung cấp cho bạn trong phạm vi Dịch vụ.
</p><p>Không được sử dụng trái phép Dịch vụ của chúng tôi. Ví dụ: không được gây trở ngại cho Dịch vụ của chúng tôi hoặc tìm cách truy cập chúng bằng phương pháp nào đó không thông qua giao diện và hướng dẫn mà chúng tôi cung cấp. Bạn chỉ có thể sử dụng Dịch vụ của chúng tôi theo như được luật pháp cho phép, bao gồm cả các luật và quy định hiện hành về quản lý xuất khẩu và tái xuất khẩu. Chúng tôi có thể tạm ngừng hoặc ngừng cung cấp Dịch vụ của chúng tôi cho bạn nếu bạn không tuân thủ các điều khoản hoặc chính sách của chúng tôi hoặc nếu chúng tôi đang điều tra hành vi bị nghi ngờ là sai phạm.
</p><p>Việc bạn sử dụng Dịch vụ của chúng tôi không có nghĩa là bạn được sở hữu bất cứ các quyền sở hữu trí tuệ nào đối với Dịch vụ của chúng tôi hoặc nội dung mà bạn truy cập. Bạn không được sử dụng nội dung từ Dịch vụ của chúng tôi trừ khi bạn được chủ sở hữu nội dung đó cho phép hoặc được luật pháp cho phép. Các điều khoản này không cấp cho bạn quyền sử dụng bất kỳ thương hiệu hoặc lôgô nào được sử dụng trong Dịch vụ của chúng tôi. Không được xóa, che khuất hoặc thay đổi bất kỳ thông báo pháp lý nào được hiển thị trong hoặc kèm theo Dịch vụ của chúng tôi.
</p><p>Dịch vụ của chúng tôi hiển thị một số nội dung không phải của Google. Chỉ một mình đối tượng cung cấp sẽ chịu trách nhiệm về nội dung này. Chúng tôi có thể xem xét nội dung để xác định xem nội dung đó có bất hợp pháp hoặc vi phạm chính sách của chúng tôi hay không, và chúng tôi có thể xóa hoặc từ chối hiển thị nội dung mà chúng tôi có lý do chính đáng để tin rằng nội dung đó vi phạm chính sách của chúng tôi hoặc luật pháp. Tuy nhiên, điều đó không nhất thiết có nghĩa là chúng tôi sẽ xem xét nội dung, do vậy bạn đừng cho rằng chúng tôi sẽ làm như vậy.
</p><p>Liên quan đến việc bạn sử dụng Dịch vụ, chúng tôi có thể gửi cho bạn các thông báo dịch vụ, thông báo quản trị và thông tin khác. Bạn có thể chọn không nhận một số thông báo này.
</p><p>Một số các Dịch vụ của chúng tôi có sẵn trên các thiết bị di động. Không sử dụng các Dịch vụ đó theo cách khiến bạn bị mất tập trung và ngăn cản bạn tuân thủ các luật về an toàn hoặc giao thông.
</p><h2 id="toc-account">Tài khoản Google của bạn</h2>
<p>Bạn có thể cần có Tài khoản Google để sử dụng một số Dịch vụ của chúng tôi. Bạn có thể tạo Tài khoản Google của riêng mình hoặc Tài khoản Google của bạn có thể được chỉ định cho bạn bởi quản trị viên, chẳng hạn như công ty tuyển dụng hoặc tổ chức giáo dục của bạn. Nếu bạn đang sử dụng Tài khoản Google được chỉ định cho bạn bởi quản trị viên, các điều khoản khác hoặc bổ sung có thể được áp dụng và quản trị viên của bạn có thể truy cập hoặc vô hiệu hóa tài khoản của bạn.
</p><p>Để bảo vệ Tài khoản Google của bạn, hãy giữ bí mật mật khẩu của bạn. Bạn chịu trách nhiệm đối với hoạt động xảy ra trên hoặc thông qua Tài khoản Google của bạn. Cố gắng không sử dụng lại mật khẩu Tài khoản Google của bạn trên các ứng dụng của bên thứ ba. Nếu bạn biết được bất kỳ hành vi sử dụng trái phép nào đối với mật khẩu hoặc Tài khoản Google của mình, <a href="http://support.google.com/accounts/bin/answer.py?hl=vi&amp;answer=58585">hãy làm theo các hướng dẫn sau</a>.
</p><h2 id="toc-protection">Bảo vệ sự riêng tư và bản quyền</h2>
<p><a href="../../policies/privacy/">Chính sách của Google về sự riêng tư</a> giải thích cách chúng tôi xử lý dữ liệu cá nhân của bạn và bảo vệ sự riêng tư của bạn khi bạn sử dụng Dịch vụ của chúng tôi. Bằng việc sử dụng Dịch vụ của chúng tôi, bạn đang đồng ý rằng Google có thể những sử dụng dữ liệu đó theo chính sách của chúng tôi về sự riêng tư.
</p><p>Chúng tôi phúc đáp các thông báo cáo buộc về vi phạm bản quyền và chấm dứt tài khoản của người tái phạm theo quy trình nêu trong Đạo luật bản quyền kỹ thuật số thiên niên kỷ của Hoa Kỳ.
</p><p>Chúng tôi cung cấp thông tin giúp chủ sở hữu bản quyền quản lý các sở hữu trí tuệ của họ trên mạng. Nếu bạn cho rằng ai đó đang vi phạm bản quyền của bạn và bạn muốn thông báo cho chúng tôi, bạn có thể tìm thông tin về cách gửi thông báo và chính sách của Google về việc phúc đáp thông báo <a href="http://support.google.com/bin/static.py?hl=vi&amp;ts=1114905&amp;page=ts.cs">tại Trung tâm trợ giúp của chúng tôi</a>.
</p><h2 id="toc-content">Nội dung của bạn trong Dịch vụ của chúng tôi</h2>
<p>Một số Dịch vụ của chúng tôi cho phép bạn tải lên, đệ trình, lưu trữ, gửi hoặc nhận nội dung. Bạn giữ quyền sở hữu mọi quyền sở hữu trí tuệ mà bạn có đối với nội dung đó. Tóm lại, những gì thuộc về bạn sẽ luôn thuộc về bạn.
</p><p>Khi bạn tải lên, đệ trình, lưu trữ, gửi hoặc nhận nội dung đến hoặc qua Dịch vụ của chúng tôi, bạn cấp cho Google (và những người chúng tôi làm việc cùng) giấy phép toàn cầu để sử dụng, làm trang chủ, lưu trữ, nhân bản, điều chỉnh, tạo các tác phẩm phái sinh (chẳng hạn như những tác phẩm có nguồn gốc từ bản dịch, phóng tác hoặc những thay đổi khác mà chúng tôi thực hiện để nội dung của bạn hoạt động tốt hơn với Dịch vụ của chúng tôi), truyền đạt, xuất bản, trình diễn công khai, hiển thị và phân phối công khai nội dung đó. Những quyền bạn cấp trong giấy phép này là nhằm phục vụ các mục đích có giới hạn như điều hành, quảng bá và cải thiện Dịch vụ của chúng tôi và để phát triển những dịch vụ mới. Giấy phép này sẽ vẫn tiếp tục có hiệu lực ngay cả nếu trong trường hợp bạn ngừng sử dụng Dịch vụ của chúng tôi (ví dụ: đối với một bản danh sách doanh nghiệp mà bạn đã thêm vào Google Maps). Một số Dịch vụ có thể cung cấp cho bạn những cách để truy cập và xóa nội dung đã được cung cấp cho Dịch vụ đó. Ngoài ra, trong một số Dịch vụ của chúng tôi, có những điều khoản hoặc cài đặt thu hẹp phạm vi sử dụng nội dung đã được gửi trong những Dịch vụ đó. Đảm bảo rằng bạn có các quyền cần thiết để cấp cho chúng tôi giấy phép này cho bất kỳ nội dung nào bạn gửi đến Dịch vụ của chúng tôi.
</p><p>Hệ thống tự động của chúng tôi phân tích nội dung của bạn (bao gồm cả email) để cung cấp cho bạn các tính năng sản phẩm có liên quan đến cá nhân, chẳng hạn như kết quả tìm kiếm tùy chỉnh, quảng cáo tùy chỉnh cũng như phát hiện spam và phần mềm độc hại. Phân tích này diễn ra khi nội dung được gửi, nhận cũng như khi được lưu trữ.
</p><p>Nếu bạn có Tài khoản Google, chúng tôi có thể hiển thị tên Profile (tên hiển thị), ảnh Profile (ảnh hiển thị) của bạn và các hành động bạn thực hiện trên Google hoặc trên các ứng dụng của bên thứ ba được kết nối với Tài khoản Google của bạn (chẳng hạn như +1s, các bài đánh giá bạn viết và những nhận xét bạn đăng) trong các Dịch vụ của chúng tôi, kể cả hiển thị trong các quảng cáo và trong các bối cảnh thương mại khác. Chúng tôi sẽ tôn trọng các lựa chọn của bạn đưa ra để giới hạn các cài đặt về mức độ hiển thị hoặc chia sẻ trong Tài khoản Google của bạn. Ví dụ: bạn có thể chọn các cài đặt sao cho tên và ảnh của bạn không xuất hiện trong một quảng cáo nào đó.
</p>
@include('vh::static.footer')
</div>
@stop